# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('uav-routing', ['internet'])
    module.includes = '.'
    module.source = [
        'model/uav-rtable.cc',
        'model/uav-packet-queue.cc',
        'model/uav-packet.cc',
        'model/uav-routing-protocol.cc',
        'helper/uav-routing-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('uav-routing')
    module_test.source = [
        'test/uav-routing-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'uav-routing'
    headers.source = [
        'model/uav-rtable.h',
        'model/uav-packet-queue.h',
        'model/uav-packet.h',
        'model/uav-routing-protocol.h',
        'helper/uav-routing-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

