# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    if not bld.env['ENABLE_EXAMPLES']:
        return;

    obj = bld.create_ns3_program('tdma-example', ['core', 'mobility', 'network', 'wifi', 'tdma', 'applications'])
    obj.source = 'tdma-example.cc'
