## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
     obj = bld.create_ns3_program('uav-routing-example', ['wifi', 'internet', 'dsdv', 'olsr',
     'uav-routing', 'applications', 'flow-monitor'])
     obj.source = 'uav-routing-example.cc'

